services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: smartgia
      POSTGRES_PASSWORD: smartgia
      POSTGRES_DB: smartgia
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartgia -d smartgia"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes: [pg_data:/var/lib/postgresql/data]

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartgia
      MONGO_INITDB_ROOT_PASSWORD: smartgia
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  auth-service:
    build:
      context: ../../
      dockerfile: services/auth-service/Dockerfile
    env_file:
      - ../../services/auth-service/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4001:4001"

  user-service:
    build:
      context: ../../
      dockerfile: services/user-service/Dockerfile
    environment:
      PORT: 4002
    depends_on:
      - auth-service
    ports:
      - "4002:4002"

  routine-service:
    build:
      context: ../../
      dockerfile: services/routine-service/Dockerfile
    environment:
      PORT: 4003
    depends_on:
      - auth-service
    ports:
      - "4003:4003"

  exercise-service:
    build:
      context: ../../
      dockerfile: services/exercise-service/Dockerfile
    environment:
      PORT: 4004
    depends_on:
      - auth-service
    ports:
      - "4004:4004"

  attendance-service:
    build:
      context: ../../
      dockerfile: services/attendance-service/Dockerfile
    environment:
      PORT: 4005
    depends_on:
      - auth-service
    ports:
      - "4005:4005"

  history-service:
    build:
      context: ../../
      dockerfile: services/history-service/Dockerfile
    environment:
      PORT: 4006
    depends_on:
      - auth-service
    ports:
      - "4006:4006"

  api-gateway:
    build:
      context: ../../
      dockerfile: services/api-gateway/Dockerfile
    environment:
      PORT: 4000
      AUTH_SERVICE_URL: "http://auth-service:4001"
      USER_SERVICE_URL: "http://user-service:4002"
      ROUTINE_SERVICE_URL: "http://routine-service:4003"
      EXERCISE_SERVICE_URL: "http://exercise-service:4004"
      ATTENDANCE_SERVICE_URL: "http://attendance-service:4005"
      HISTORY_SERVICE_URL: "http://history-service:4006"
    depends_on:
      - auth-service
      - user-service
      - routine-service
      - exercise-service
      - attendance-service
      - history-service
    ports:
      - "4000:4000"

volumes:
  pg_data:
  mongo_data:
